// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evdnxollhrhsttloffct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZG54b2xsaHJoc3R0bG9mZmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTY0NzMsImV4cCI6MjA3NDEzMjQ3M30.gqlMRMHUOxhNrKTN0uF3R6kJcY7J81Uukpl91ZYOC3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});