// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgmlfcmagyzshhdmuomy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnbWxmY21hZ3l6c2hoZG11b215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzA2ODgsImV4cCI6MjA2ODEwNjY4OH0.HGCHNDzuYrlZkuHMxCugi_R-Iuvdo8J-Y000cuwKkys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});